Repository react-native-async-storage/async-storage, pull requests merged in 2019-07, with the labels that each got.

#136 [v2] Initial Core implementation
  .circleci/config.yml
  .prettierrc
  babel.config.js
  core/__tests__/AsyncStorage.test.ts
  core/__tests__/core.test.ts
  core/src/AsyncStorage.ts
  core/src/defaults.ts
  core/src/index.ts
  core/types/index.d.ts
  jest.config.js
  package.json
  tsconfig.json
  yarn.lock
Labels: WIP, v2

#146 Add trailing `/` to `transformIgnorePatterns`
  docs/Jest-integration.md
Labels: Docs, LEGACY

#150 Update docs to cover auto-linking
  .circleci/config.yml
  README.md
Labels: Docs, LEGACY

#155 Add ios build directory to .npmignore
  .npmignore
Labels: LEGACY, Platform: iOS

#154 fix: broken link in AsyncStorage.js
  lib/AsyncStorage.js
Labels: Docs, LEGACY

#166 fix: getAllKeys() Jest mock returns array of keys
  jest/async-storage-mock.js
Labels: LEGACY

#167 Add tvOS to podspec supported platforms
  RNCAsyncStorage.podspec
Labels: LEGACY, Platform: iOS

#160 The AsyncTask.THREAD_POOL_EXECUTOR maybe blocked by some other module
  android/build.gradle
  android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java
Labels: LEGACY, Platform: Android

#171 Dedicated executor docs
  docs/advanced/DedicatedExecutor.md
  example/android/gradle.properties
Labels: Docs, LEGACY
