Repository react-native-async-storage/async-storage, pull requests merged in 2019-06, with the labels that each got.

#119 Fixes 'RNCAsyncStorage/RNCAsyncStorageDelegate.h' file not found
  ios/RNCAsyncStorage.h
Labels: Platform: iOS

#121 feat: Migrate Async Storage v1 to LEGACY
  .circleci/config.yml
  .releaserc
  package.json
  yarn.lock
Labels: Enhancement

#123 fix: Allow void for ItemGetCallbackType in mock storage
  jest/async-storage-mock.js
Labels: LEGACY
