Repository react-native-async-storage/async-storage, pull requests merged in 2019-05, with the labels that each got.

#93 Podspecs: correct git tag format
  RNCAsyncStorage.podspec
Labels: Bug, PR ready :100:, Platform: iOS

#95 chore: upgrade detox
  example/android/app/build.gradle
  example/android/app/src/androidTest/java/com/asyncstorageexample/DetoxTest.java
  example/android/build.gradle
  example/android/settings.gradle
  package.json
  yarn.lock
Labels: Bug, Platform: iOS

#100 docs: add info that storage is still unencrypted
  README.md
Labels: Docs

#109 Add tvOS to supported platforms
  ios/RNCAsyncStorage.xcodeproj/project.pbxproj
Labels: Platform: iOS

#114 chore: add things to try for common issues
  docs/Troubleshooting.md
Labels: Docs
