Repository react-native-async-storage/async-storage, pull requests merged in 2019-12, with the labels that each got.

#261 fix(iOS): Remove RNC -> RCT storage migration
  packages/storage-legacy/ios/RNCAsyncStorage.m
Labels: Platform: iOS, v2

#259 fix(android): throw error when value is `null`
  lib/AsyncStorage.js
Labels: LEGACY

#254 [chore] Preparation for RC
  .circleci/config.yml
  .circleci/scripts/run_android_e2e.sh
  .circleci/scripts/run_ios_e2e.sh
  .github/ISSUE_TEMPLATE/02_feature_request.md
  .github/ISSUE_TEMPLATE/03_question_discussion.md
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/help.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  docs/OLD/API.md
  docs/OLD/Jest-integration.md
  docs/OLD/Troubleshooting.md
  package.json
  packages/core/README.md
  packages/core/docs/API.md
  packages/core/docs/Usage.md
  packages/core/package.json
  packages/storage-legacy/docs/Linking.md
  packages/storage-legacy/docs/advanced/BrownfieldIntegration.md
  packages/storage-legacy/docs/advanced/IncreaseDbSize.md
  packages/storage-legacy/package.json
  packages/storage-legacy/src/index.ts
  packages/storage-web/package.json
Labels: v2
