Repository react-native-async-storage/async-storage, pull requests merged in 2019-04, with the labels that each got.

#60 [chore] Changes regarding cutting a release
  .circleci/config.yml
  .releaserc
  CONTRIBUTING.md
Labels: Enhancement

#53 [feat] Jest mocks, AsyncStorage testing guidelines
  .circleci/config.yml
  README.md
  docs/Jest-integration.md
  example/__tests__/App.js
  example/e2e/asyncstorage.e2e.js
  example/e2e/config.json
  example/jest.setup.js
  jest/async-storage-mock.js
  lib/AsyncStorage.js
  lib/hooks.js
  lib/index.js
  package.json
Labels: Enhancement

#66 Deprecate AsyncStorage from React Native
  lib/AsyncStorage.js
Labels: Enhancement, Platform: iOS

#61 docs: Update iOS Linking information
  README.md
  docs/Linking.md
Labels: Docs

#35 feat: Allow brownfield iOS apps to handle storage.
  README.md
  docs/AdvancedUsage.md
  example/e2e/asyncstorage.e2e.js
  example/ios/AsyncStorageExample.xcodeproj/project.pbxproj
  example/ios/AsyncStorageExample/AppDelegate+RNCAsyncStorageDelegate.h
  example/ios/AsyncStorageExample/AppDelegate+RNCAsyncStorageDelegate.m
  example/ios/AsyncStorageExample/AppDelegate.h
  example/ios/AsyncStorageExample/AppDelegate.m
  example/ios/AsyncStorageExample/Info.plist
  example/ios/AsyncStorageExample/RNCTestAsyncStorageDelegate.h
  example/ios/AsyncStorageExample/RNCTestAsyncStorageDelegate.m
  ios/RNCAsyncStorage.h
  ios/RNCAsyncStorage.m
  ios/RNCAsyncStorage.xcodeproj/project.pbxproj
  ios/RNCAsyncStorageDelegate.h
Labels: Enhancement, Platform: iOS

#70 [chore] Keep up with Release
  .releaserc
  package.json
Labels: Released

#57 React Native peer dependency warning
  package.json
Labels: Docs

#71 [chore] Setup semantic releases on master
  .circleci/config.yml
  .releaserc
  CONTRIBUTING.md
Labels: Docs

#64 iOS clean migration from RNCAsyncStorage_V1 to RTCAsyncStorage_V1
  ios/RNCAsyncStorage.m
Labels: Enhancement, Platform: iOS
